//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortalSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE
    {
        public int ATTENDANCE_ID { get; set; }
        public System.DateTime ATTENDANCE_DATE { get; set; }
        public string STATUS { get; set; }
        public int ENROLLMENT_ID { get; set; }
    
        public virtual ENROLLMENT ENROLLMENT { get; set; }
    }
}
