//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortalSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COURS()
        {
            this.ENROLLMENTS = new HashSet<ENROLLMENT>();
            this.FEES = new HashSet<FEE>();
            this.TRANSCRIPTs = new HashSet<TRANSCRIPT>();
        }
    
        public int COURSE_ID { get; set; }
        public string COURSE_NAME { get; set; }
        public int CREDITS { get; set; }
        public int TEACHER_ID { get; set; }
        public double AMOUNT_PER_COURSE { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual TEACHER TEACHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENROLLMENT> ENROLLMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEE> FEES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSCRIPT> TRANSCRIPTs { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
