//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortalSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENROLLMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENROLLMENT()
        {
            this.ATTENDANCEs = new HashSet<ATTENDANCE>();
            this.GRADES = new HashSet<GRADE>();
        }
    
        public int ENROLLMENT_ID { get; set; }
        public int STUDENT_ID { get; set; }
        public int COURSE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTENDANCE> ATTENDANCEs { get; set; }
        public virtual COURS COURS { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADE> GRADES { get; set; }
    }
}
