//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortalSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRADE()
        {
            this.TRANSCRIPTs = new HashSet<TRANSCRIPT>();
        }
    
        public int GRADE_ID { get; set; }
        public int ENROLLMENT_ID { get; set; }
        public Nullable<int> MARKS { get; set; }
        public string GRADE1 { get; set; }
    
        public virtual ENROLLMENT ENROLLMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSCRIPT> TRANSCRIPTs { get; set; }
    }
}
