//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortalSystemMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentPortalSystemEntities : DbContext
    {
        public StudentPortalSystemEntities()
            : base("name=StudentPortalSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATTENDANCE> ATTENDANCEs { get; set; }
        public virtual DbSet<COURS> COURSES { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTS { get; set; }
        public virtual DbSet<ENROLLMENT> ENROLLMENTS { get; set; }
        public virtual DbSet<FEE> FEES { get; set; }
        public virtual DbSet<GRADE> GRADES { get; set; }
        public virtual DbSet<STUDENT> STUDENTS { get; set; }
        public virtual DbSet<TEACHER> TEACHERS { get; set; }
        public virtual DbSet<TRANSCRIPT> TRANSCRIPTs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<CourseRegistrationStatu> CourseRegistrationStatus { get; set; }
    }
}
