//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortalSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSCRIPT
    {
        public int TRANSCRIPT_ID { get; set; }
        public int COURSE_ID { get; set; }
        public int STUDENT_ID { get; set; }
        public int GRADE_ID { get; set; }
        public Nullable<double> SGPA { get; set; }
        public Nullable<double> CGPA { get; set; }
    
        public virtual COURS COURS { get; set; }
        public virtual GRADE GRADE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
